name: hue_dart
description: A library for creating Philips Hue apps in Flutter and/or AngularDart.
version: 0.1.1
homepage: https://github.com/Jairzinno/hue_dart
author: Jairzinno Henriquez <jairzinnohenriquez@gmail.com>

environment:
  sdk: '>=2.0.0-dev.69.0 <3.0.0'

dependencies:
 intl: "^0.15.6"
 json_serializable: "^0.5.8"
 http: "^0.11.3+16"
 math: "^0.9.0"

dev_dependencies:
  build_runner:
  test: ^0.12.30
  mockito: "^2.2.3"
