name: hue_dart
description: A library for creating Philips Hue apps in Flutter and/or AngularDart.
version: 0.3.0
homepage: https://github.com/Jairzinno/hue_dart
author: Jairzinno Henriquez <jairzinnohenriquez@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 intl: ^0.17.0
 http: ^0.13.2
 built_value: ^8.0.5
 built_collection: ^5.0.0

dev_dependencies:
  test: ^1.17.3
  mockito: ^5.0.7
  built_value_generator: ^8.0.5