name: hue_dart
description: A library for creating Philips Hue apps in Flutter and/or AngularDart.
version: 0.1.2
homepage: https://github.com/Jairzinno/hue_dart
author: Jairzinno Henriquez <jairzinnohenriquez@gmail.com>

environment:
  sdk: '>=2.0.0-dev.69.0 <3.0.0'

dependencies:
 intl: "^0.15.6"
 http: "^0.11.3+16"
 json_serializable: "^2.0.1"
 built_collection: '>=2.0.0 <5.0.0'
 built_value: '>=5.5.5 <7.0.0'

dev_dependencies:
  build_runner:
  test: "^1.2.0"
  mockito: "^3.0.0"
  built_value_generator: ^6.1.6
