name: hue_dart
description: A library for creating Philips Hue apps in Flutter and/or AngularDart.
version: 0.2.1
homepage: https://github.com/Jairzinno/hue_dart
author: Jairzinno Henriquez <jairzinnohenriquez@gmail.com>

environment:
  sdk: '>=2.6.1 <3.0.0'

dependencies:
 intl: ^0.16.0
 http: ^0.12.0+2
 built_value: ^7.0.0
 built_collection: ^4.2.2

dev_dependencies:
  test: ^1.9.3
  mockito: ^4.1.1
  built_value_generator: ^7.0.0
   