name: hue_dart
description: A library for creating Philips Hue apps in Flutter and/or AngularDart.
version: 0.3.1
homepage: https://github.com/Jairzinno/hue_dart

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
 built_collection: ^5.1.1
 built_value: ^8.6.3
 http: ^1.1.0
 intl: ^0.18.1
 network_tools: ^3.2.1

dev_dependencies:
 built_value_generator: ^8.6.3
 lint: ^2.1.2
 mockito: ^5.4.2
 test: ^1.24.6
