name: hue_dart
description: A library for creating Philips Hue apps in Flutter and/or AngularDart.
version: 0.1.2
homepage: https://github.com/Jairzinno/hue_dart
author: Jairzinno Henriquez <jairzinnohenriquez@gmail.com>

environment:
  sdk: '>=2.0.0-dev.69.0 <3.0.0'

dependencies:
 intl: "^0.15.6"
 http: "^0.11.3+16"
 json_serializable: "^0.5.8"

dev_dependencies:

  build_runner:
  test: "^1.2.0"
  mockito: "^3.0.0"
