name: hue_dart
description: A library for creating Philips Hue apps in Flutter and/or AngularDart.
version: 0.3.0
homepage: https://github.com/Jairzinno/hue_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 built_collection: ^5.1.1
 built_value: ^8.4.3
 http: ^0.13.5
 intl: ^0.18.0
 # TODO: Switch to the pub.dev pacakge whenever there is newer version then 3.0.0 as it missing
 # mdns features
 network_tools:
  git:
   url: 'https://github.com/guyluz11/network_tools.git'
   path: 'network_tools'


dev_dependencies:
 built_value_generator: ^8.4.3
 lint: ^2.0.1
 mockito: ^5.3.2
 test: ^1.22.2
